# Uncomment to enable encoder
# CONFIG_EC11=y
# CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# --- Split keyboard ---
CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y

# --- Wired split transport ---
CONFIG_ZMK_SPLIT_WIRED=y

# UART mode (nRF52 поддерживает interrupt mode)
CONFIG_ZMK_SPLIT_WIRED_UART_MODE_INTERRUPT=y

# --- Display ---
CONFIG_ZMK_DISPLAY=y

# --- General keyboard options ---
CONFIG_ZMK_USB=y
CONFIG_ZMK_BLE=y

# Debounce
CONFIG_ZMK_KSCAN_DEBOUNCE_PRESS_MS=5
CONFIG_ZMK_KSCAN_DEBOUNCE_RELEASE_MS=5

# Power saving
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=600000
